name: Push Code

permissions: write-all

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: set username and email
      run: |
        git config user.name  ${{secrets.USER_NAME}}
        git config user.email ${{secrets.USER_EMAIL}}

    - name: version upgrade
      run: npm version patch

    - name: push code
      run: git push origin master
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Publish to NPM
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
      run: npm publish
